# Project Metadata
name: invoshop
description: "Invoshop"
publish_to: 'none'
version: 1.0.0

# Environment Constraints
environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  http: ^1.3.0
  shared_preferences: ^2.5.2
  fluttertoast: ^8.2.12
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.3
  flutter_onboarding_slider: ^1.0.11
  flutter_svg: ^2.0.17
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  animated_custom_dropdown: ^3.1.1
  connectivity_plus: ^6.1.3
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  webview_flutter: ^4.10.0
  flutter_rounded_date_picker: ^3.0.4
  shimmer: ^3.0.0
  flutter_widget_from_html_core: ^0.16.0

# Development Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  image_path: "assets/logos/app_logo.png"
  android: true
  ios: true

# Flutter Configuration
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/logos/
    - assets/onboarding/
    - assets/icons/
    - assets/icons/profile/
    - assets/icons/drawer/
    - assets/images/banners/
    - assets/images/category/
    - assets/images/products/
    - assets/images/drawer_image/
    - assets/images/sign_up/
    - assets/images/combo/
    - assets/gif/
    - assets/images/others/

