import 'package:invoshop/common/widgets/screen_not_found/screen_not_found.dart';
import 'package:invoshop/screens/about/views/about_screen.dart';
import 'package:invoshop/screens/admin%20_and_vendor_products/view/add_product/add_product.dart';
import 'package:invoshop/screens/admin%20_and_vendor_products/view/admin_and_vendor_products_screen.dart';
import 'package:invoshop/screens/admin%20_and_vendor_products/view/brand_management/brand_management.dart';
import 'package:invoshop/screens/admin%20_and_vendor_products/view/category_management/category_management.dart';
import 'package:invoshop/screens/admin%20_and_vendor_products/view/unit_management/unit_managemen.dart';
import 'package:invoshop/screens/authentication/become_a_seller/view/become_a_seller_screen.dart';
import 'package:invoshop/screens/authentication/change_password/views/change_password.dart';
import 'package:invoshop/screens/authentication/find_domain/view/find_domain_screen.dart';
import 'package:invoshop/screens/authentication/forgot/forgotten_pass_screen.dart';
import 'package:invoshop/screens/authentication/sign_in/views/sign_in_screen.dart';
import 'package:invoshop/screens/authentication/sign_up/views/sign_up_screen.dart';
import 'package:invoshop/screens/bank_accounts/view/bank_account/add_new_bank_account_screen.dart';
import 'package:invoshop/screens/bank_accounts/view/bank_accounts_screen.dart';
import 'package:invoshop/screens/billers/view/billers_screen.dart';
import 'package:invoshop/screens/brand/views/brand_screen.dart';
import 'package:invoshop/screens/cart/views/cart_screen.dart';
import 'package:invoshop/screens/category/views/category_screen.dart';
import 'package:invoshop/screens/combo_offers/views/combo_offer_screen.dart';
import 'package:invoshop/screens/contact/views/contact_screen.dart';
import 'package:invoshop/screens/customer/view/customer_screen.dart';
import 'package:invoshop/screens/expense/view/expense_screen.dart';
import 'package:invoshop/screens/home/views/home_screen.dart';
import 'package:invoshop/screens/new_order/view/new_order_screen.dart';
import 'package:invoshop/screens/on_boarding/view/on_boarding_screen.dart';
import 'package:invoshop/screens/order_return/view/order_return_screen.dart';
import 'package:invoshop/screens/orders/view/customer_orders_screen.dart';
import 'package:invoshop/screens/orders/view/orders_screen.dart';
import 'package:invoshop/screens/overview/view/overview_screen.dart';
import 'package:invoshop/screens/pos/view/pos_screen.dart';
import 'package:invoshop/screens/products/views/products_screen.dart';
import 'package:invoshop/screens/profile/views/profile_screen.dart';
import 'package:invoshop/screens/profile/views/sub_sections/my_coupon/views/coupon_screen.dart';
import 'package:invoshop/screens/profile/views/sub_sections/orders_history/views/order_history_screen.dart';
import 'package:invoshop/screens/profile/views/sub_sections/reviews/views/reviews_screen.dart';
import 'package:invoshop/screens/profile/views/sub_sections/track_order/views/track_order_screen.dart';
import 'package:invoshop/screens/profile/views/sub_sections/transactions/transactions_screen.dart';
import 'package:invoshop/screens/refund_policy/views/refund_screen.dart';
import 'package:invoshop/screens/report/view/report_screen.dart';
import 'package:invoshop/screens/reviews/view/user_reviews_screen.dart';
import 'package:invoshop/screens/sale/view/sale_screen.dart';
import 'package:invoshop/screens/splash/view/splash_screen.dart';
import 'package:invoshop/screens/supplier/view/supplier_screen.dart';
import 'package:invoshop/screens/termsCondition/views/terms_conditions_screen.dart';
import 'package:invoshop/screens/user_management/view/user_management_screen.dart';
import 'package:invoshop/screens/warehouse/view/warehouse_screen.dart';
import 'package:invoshop/screens/wishlist/views/wishlist_screen.dart';

class RoutesConfig {
  static const pageNotFound = ScreenNotFound();
  static const splash = SplashScreen();
  static const onBoarding = OnboardingScreen();
  static const category = CategoryScreen();
  static const home = HomeScreen();
  static const transactions = TransactionsScreen();
  static const products = ProductsScreen();
  static const cart = CartScreen();
  static const wishlist = WishlistScreen();
  static const findDomain = FindDomainScreen();
  static const becomeASeller = BecomeASellerScreen();
  static const brand = BrandScreen();
  static const comboOffer = ComboOfferScreen();
  static const about = AboutScreen();
  static const contact = ContactScreen();
  static const termsCondition = TermsConditionsScreen();
  static const refundPolicy = RefundScreen();
  static const signIn = SignInScreen();
  static const signUp = SignUpScreen();
  static const forgotPass = ForgottenPassScreen();
  static const changePassword = ChangePassword();
  static const profile = ProfileScreen();
  static const orderHistory = OrderHistoryScreen();
  static const reviews = ReviewsScreen();
  static const myCoupon = CouponScreen();
  static const trackOrder = TrackOrderScreen();
  static const newOrder = NewOrderScreen();
  static const orders = OrdersScreen();
  static const overView = OverviewScreen();
  static const userReviews = UserReviewsScreen();
  static const orderReturn = OrderReturnScreen();
  static const bankAccount = BankAccountsScreen();
  static const addNewBankAccount = AddNewBankAccountScreen();
  static const adminAndVendorProducts = AdminAndVendorProductsScreen();
  static const expense = ExpenseScreen();
  static const pos = PosScreen();
  static const userManagement = UserManagementScreen();
  static const customer = CustomerScreen();
  static const supplier = SupplierScreen();
  static const billers = BillersScreen();
  static const warehouse = WarehouseScreen();
  static const reports = ReportScreen();
  static const sale = SaleScreen();
  static const unitManagement = UnitManagement();
  static const brandManagement = BrandManagement();
  static const categoryManagement = CategoryManagement();
  static const addProduct = AddProduct();
  static const customerOrders = CustomerOrdersScreen();
}
