import 'package:ai_store/common/widgets/screen_not_found/screen_not_found.dart';
import 'package:ai_store/screens/about/views/about_screen.dart';
import 'package:ai_store/screens/admin%20_and_vendor_products/view/admin_and_vendor_products_screen.dart';
import 'package:ai_store/screens/authentication/become_a_seller/view/become_a_seller_screen.dart';
import 'package:ai_store/screens/authentication/change_password/views/change_password.dart';
import 'package:ai_store/screens/authentication/find_supplier/view/find_supplier_screen.dart';
import 'package:ai_store/screens/authentication/forgot/forgotten_pass_screen.dart';
import 'package:ai_store/screens/authentication/otp/views/otp_screen.dart';
import 'package:ai_store/screens/authentication/sign_in/views/sign_in_screen.dart';
import 'package:ai_store/screens/authentication/sign_up/views/sign_up_screen.dart';
import 'package:ai_store/screens/brand/views/brand_screen.dart';
import 'package:ai_store/screens/cart/views/cart_screen.dart';
import 'package:ai_store/screens/category/views/category_screen.dart';
import 'package:ai_store/screens/combo_offers/views/combo_offer_screen.dart';
import 'package:ai_store/screens/contact/views/contact_screen.dart';
import 'package:ai_store/screens/customer/view/customer_screen.dart';
import 'package:ai_store/screens/expense/view/expense_screen.dart';
import 'package:ai_store/screens/home/views/home_screen.dart';
import 'package:ai_store/screens/new_order/view/new_order_screen.dart';
import 'package:ai_store/screens/on_boarding/view/on_boarding_screen.dart';
import 'package:ai_store/screens/order_return/view/order_return_screen.dart';
import 'package:ai_store/screens/orders/view/orders_screen.dart';
import 'package:ai_store/screens/overview/view/overview_screen.dart';
import 'package:ai_store/screens/payment/view/bank_account/add_new_bank_account_screen.dart';
import 'package:ai_store/screens/payment/view/payment_screen.dart';
import 'package:ai_store/screens/pos/view/pos_screen.dart';
import 'package:ai_store/screens/products/views/products_screen.dart';
import 'package:ai_store/screens/profile/views/profile_screen.dart';
import 'package:ai_store/screens/profile/views/sub_sections/my_coupon/views/coupon_screen.dart';
import 'package:ai_store/screens/profile/views/sub_sections/orders_history/views/order_history_screen.dart';
import 'package:ai_store/screens/profile/views/sub_sections/reviews/views/reviews_screen.dart';
import 'package:ai_store/screens/profile/views/sub_sections/track_order/views/track_order_screen.dart';
import 'package:ai_store/screens/profile/views/sub_sections/transactions/transactions_screen.dart';
import 'package:ai_store/screens/refund_policy/views/refund_screen.dart';
import 'package:ai_store/screens/splash/view/splash_screen.dart';
import 'package:ai_store/screens/termsCondition/views/terms_conditions_screen.dart';
import 'package:ai_store/screens/user_management/view/user_management_screen.dart';
import 'package:ai_store/screens/vendor_reviews/view/vendor_reviews_screen.dart';
import 'package:ai_store/screens/wishlist/views/wishlist_screen.dart';

class RoutesConfig {
  static const pageNotFound = ScreenNotFound();
  static const splash = SplashScreen();
  static const onBoarding = OnboardingScreen();
  static const category = CategoryScreen();
  static const home = HomeScreen();
  static const transactions = TransactionsScreen();
  static const products = ProductsScreen();
  static const cart = CartScreen();
  static const wishlist = WishlistScreen();
  static const findSupplier = FindSupplierScreen();
  static const becomeASeller = BecomeASellerScreen();
  static const brand = BrandScreen();
  static const comboOffer = ComboOfferScreen();
  static const about = AboutScreen();
  static const contact = ContactScreen();
  static const termsCondition = TermsConditionsScreen();
  static const refundPolicy = RefundScreen();
  static const signIn = SignInScreen();
  static const signUp = SignUpScreen();
  static const forgotPass = ForgottenPassScreen();
  static const changePassword = ChangePassword();
  static const otp = OtpScreen();
  static const profile = ProfileScreen();
  static const orderHistory = OrderHistoryScreen();
  static const reviews = ReviewsScreen();
  static const myCoupon = CouponScreen();
  static const trackOrder = TrackOrderScreen();
  static const newOrder = NewOrderScreen();
  static const orders = OrdersScreen();
  static const overView = OverviewScreen();
  static const vendorReviews = VendorReviewsScreen();
  static const orderReturn = OrderReturnScreen();
  static const payment = PaymentScreen();
  static const addNewBankAccount = AddNewBankAccountScreen();
  static const adminAndVendorProducts = AdminAndVendorProductsScreen();
  static const expense = ExpenseScreen();
  static const pos = PosScreen();
  static const userManagement = UserManagementScreen();
  static const customer = CustomerScreen();
}
